// streetsNames1030
const streetNames1030 = [
    "allée des freesias",
    "avenue albert giraud",
    "avenue charles gilisquet",
    "avenue de la reine",
    "avenue de roodebeek",
    "avenue des jacinthes",
    "avenue docteur dejase",
    "avenue émile verhaeren",
    "avenue émile zola",
    "avenue ernest cambier",
    "avenue eugène plasky",
    "avenue félix marchal",
    "avenue frans courtens",
    "avenue général eisenhower",
    "avenue georges eekhoud",
    "avenue gustave latinis",
    "avenue herbert hoover",
    "avenue huart hamoir",
    "avenue jacques georgin",
    "avenue jean jaurès",
    "avenue louis bertrand",
    "avenue maréchal foch",
    "avenue maurice maeterlinck",
    "avenue monplaisir",
    "avenue paul deschanel",
    "avenue philippe thomas",
    "avenue princesse elisabeth",
    "avenue rogier",
    "avenue sleeckx",
    "avenue voltaire",
    "boulevard auguste reyers",
    "boulevard du roi albert ii",
    "boulevard général wahis",
    "boulevard lambermont",
    "boulevard simon bolivar",
    "chaussée de haecht",
    "chaussée de helmet",
    "chaussée de louvain",
    "grande rue au bois",
    "petite rue des secours",
    "petite rue l'olivier",
    "place colignon",
    "place de la reine",
    "place des bienfaiteurs",
    "place des carabiniers",
    "place eugène verboekhoven",
    "place général meiser",
    "place lehon",
    "place liedts",
    "place princesse elisabeth",
    "place solvay",
    "place stephenson",
    "rue achille detienne",
    "rue adolphe marbotin",
    "rue alexandre markelbach",
    "rue anatole france",
    "rue andré van hasselt",
    "rue armand de roo",
    "rue auguste lambiotte",
    "rue auguste snieders",
    "rue camille simoens",
    "rue caporal claes",
    "rue charles meert",
    "rue chaumontel",
    "rue colonel bourg",
    "rue creuse",
    "rue d'aerschot",
    "rue de beughem",
    "rue de brabant",
    "rue de la bruyère",
    "rue de la consolation",
    "rue de la fraternité",
    "rue de la luzerne",
    "rue de la marne",
    "rue de la poste",
    "rue de l'agriculture",
    "rue de l'est",
    "rue de linthout",
    "rue de locht",
    "rue de potter",
    "rue de quatrecht",
    "rue de robiano",
    "rue des coteaux",
    "rue des palais",
    "rue des pâquerettes",
    "rue des pensées",
    "rue docteur élie lambotte",
    "rue du corbeau",
    "rue du dahlia",
    "rue du foyer schaerbeekois",
    "rue du noyer",
    "rue du pavillon",
    "rue du progrès",
    "rue du radium",
    "rue du saphir",
    "rue du tilleul",
    "rue dupont",
    "rue émile wittmann",
    "rue fernand séverin",
    "rue général eenens",
    "rue georges garnir",
    "rue guido gezelle",
    "rue guillaume kennis",
    "rue gustave fuss",
    "rue gustave huberti",
    "rue henri bergé",
    "rue henri chomé",
    "rue henri evenepoel",
    "rue henri jacobs",
    "rue henri stacquet",
    "rue jacques jansen",
    "rue james watt",
    "rue jan blockx",
    "rue josaphat",
    "rue joseph van camp",
    "rue joseph wauters",
    "rue jules lebrun",
    "rue kessels",
    "rue lefrancq",
    "rue léon mignon",
    "rue marguerite van de wiele",
    "rue massaux",
    "rue maurice des ombiaux",
    "rue max roos",
    "rue metsys",
    "rue monrose",
    "rue nestor de tière",
    "rue nicolas defrêcheux",
    "rue paul devigne",
    "rue pierre theunis",
    "rue portaels",
    "rue rasson",
    "rue richard vandevelde",
    "rue rogier",
    "rue royale-sainte-marie",
    "rue sander pierron",
    "rue seutin",
    "rue stephenson",
    "rue stijn streuvels",
    "rue théodore roosevelt",
    "rue thiéfry",
    "rue thomas vinçotte",
    "rue van droogenbroeck",
    "rue van dyck",
    "rue vandenbussche",
    "rue vandermeersch",
    "rue vandeweyer",
    "rue verboeckhaven",
    "rue vergote",
    "rue verhas",
    "rue verwée",
    "rue victor lefèvre",
    "rue vonck",
    "rue waelhem",
    "square françois riga",
    "square levie",
    "square prévost-delaunay",
    "square vergote"
];

const streetNames1030_ALL = [
    "allée des freesias",
    "avenue adolphe lacomblé",
    "avenue albert desenfans",
    "avenue albert giraud",
    "avenue ambassadeur van vollenhoven",
    "avenue britisiers",
    "avenue cambier ernest",
    "avenue charbo",
    "avenue charles gilisquet",
    "avenue chazal",
    "avenue clays",
    "avenue colonel picquart",
    "avenue courtens frans",
    "avenue dailly",
    "avenue de la brabançonne",
    "avenue de la jeunesse",
    "avenue de la reine",
    "avenue de la topaze",
    "avenue de l'emeraude",
    "avenue de l'héliport",
    "avenue de l'opale",
    "avenue de mars",
    "avenue de rodenbach",
    "avenue de roodebeek",
    "avenue des capucines",
    "avenue des cerisiers",
    "avenue des clos",
    "avenue des glycines",
    "avenue des héliotropes",
    "avenue des jacinthes",
    "avenue des jardins",
    "avenue deschanel paul",
    "avenue docteur dejase",
    "avenue du diamant",
    "avenue du suffrage universel",
    "avenue eeckhoud georges",
    "avenue emile max",
    "avenue emile verhaeren",
    "avenue emile zola",
    "avenue ernest cambier",
    "avenue ernest renan",
    "avenue eugène plasky",
    "avenue felix marchal",
    "avenue fortin",
    "avenue frans courtens",
    "avenue general eisenhower",
    "avenue georges eeckhoud",
    "avenue georgin jacques",
    "avenue gilisquet charles",
    "avenue herbert hoover",
    "avenue hoover herbert",
    "avenue huart hamoir",
    "avenue jacques georgin",
    "avenue jan stobbaerts",
    "avenue jaurès jean",
    "avenue jean jaurès",
    "avenue latinis",
    "avenue latinis gustave",
    "avenue léon mahillon",
    "avenue louis bertrand",
    "avenue maeterlinck maurice",
    "avenue maréchal foch",
    "avenue maurice maeterlinck",
    "avenue milcamps",
    "avenue monplaisir",
    "avenue paul deschanel",
    "avenue philippe thomas",
    "avenue plasky eugène",
    "avenue princesse elisabeth",
    "avenue raymond foucart",
    "avenue rogier",
    "avenue sleeckx",
    "avenue thomas philippe",
    "avenue verhaeren emile",
    "avenue voltaire",
    "avenue zénobe gramme",
    "avenues des azalées",
    "boulevard albert ii",
    "boulevard auguste reyers",
    "boulevard bolivar simon",
    "boulevard général wahis",
    "boulevard lambermont",
    "boulevard léopold iii",
    "boulevard simon bolivar",
    "chaussée de haecht",
    "chaussée de helmet",
    "chaussée de louvain",
    "chaussée haecht",
    "chaussée louvain",
    "chemin du forgeron",
    "clos des artistes",
    "clos des fleurs",
    "clos des mouettes",
    "clos des poètes",
    "clos du chemin creux",
    "drève recteur van waeyenbergh",
    "grande rue au bois",
    "petite rue des secours",
    "petite rue l'olivier",
    "place bremer",
    "place colignon",
    "place colonel bremer",
    "place dailly",
    "place de houffalize",
    "place de jamblinne de meux",
    "place de la patrie",
    "place de la reine",
    "place des bienfaiteurs",
    "place des carabiniers",
    "place des chasseurs ardennais",
    "place du pavillon",
    "place gaucheret",
    "place général meiser",
    "place lehon",
    "place liedts",
    "place masui",
    "place princesse elisabeth",
    "place solvay",
    "place stephenson",
    "place terdelt",
    "place verboekhoven",
    "place wappers",
    "rue achiel detienne",
    "rue adolphe marbotin",
    "rue aimé smekens",
    "rue albert de latour",
    "rue alexandre de craene",
    "rue alexandre markelbach",
    "rue alfred verwée",
    "rue allard",
    "rue anatole france",
    "rue andré van hasselt",
    "rue armand de roo",
    "rue artan",
    "rue arthur roland",
    "rue auguste snieders",
    "rue augustre lambiotte",
    "rue bergé henri",
    "rue brichaut",
    "rue camille simoens",
    "rue camille wollès",
    "rue caporal claes",
    "rue capronnier",
    "rue charles meert",
    "rue charles van lerberghe",
    "rue charles vanderstappen",
    "rue chaumontel",
    "rue colonel bourg",
    "rue cornet de grez",
    "rue creuse",
    "rue d'aerschot",
    "rue d'anethan",
    "rue de beughem",
    "rue de brabant",
    "rue de cologne",
    "rue de genève",
    "rue de jérusalem",
    "rue de la bruyère",
    "rue de la chaumière",
    "rue de la cible",
    "rue de la consolation",
    "rue de la constitution",
    "rue de la fraternité",
    "rue de la luzerne",
    "rue de la marne",
    "rue de la poste",
    "rue de la ruche",
    "rue de l'agriculture",
    "rue de l'est",
    "rue de linthout",
    "rue de locht",
    "rue de l'orme",
    "rue de moerkerke",
    "rue de potter",
    "rue de quatrecht",
    "rue de robiano",
    "rue de roo armand",
    "rue de tière nestor",
    "rue degouve de nuncques",
    "rue degreef françois",
    "rue des ailes",
    "rue des chardons",
    "rue des compagnons",
    "rue des coteaux",
    "rue des mimosas",
    "rue des ombiaux",
    "rue des palais",
    "rue des pâquerettes",
    "rue des pavots",
    "rue des pensées",
    "rue des plantes",
    "rue désiré desmet",
    "rue destouvelles",
    "rue devigne paul",
    "rue d'hoogvorst",
    "rue docteur elie lambotte",
    "rue du corbeau",
    "rue du dahlia",
    "rue du foyer schaerbeekois",
    "rue du noyer",
    "rue du pavillon",
    "rue du progrès",
    "rue du radium",
    "rue du saphir",
    "rue du soleil",
    "rue du tilleul",
    "rue dupont",
    "rue edouard fiers",
    "rue emile wittmann",
    "rue emmanuel hiel",
    "rue ernest discailles",
    "rue ernest laude",
    "rue eugène smits",
    "rue fernand séverin",
    "rue floris",
    "rue fontaine d'amour",
    "rue fraikin",
    "rue françois bossaerts",
    "rue françois degreef",
    "rue françois-joseph navez",
    "rue frans binjé",
    "rue frédéric pelletier",
    "rue fuss gustave",
    "rue gallait",
    "rue gaucheret",
    "rue geefs",
    "rue gendebien",
    "rue général eenens",
    "rue général gratry",
    "rue georges garnir",
    "rue georges raeymaekers",
    "rue godefroid devreese",
    "rue godefroid guffens",
    "rue goosens",
    "rue grégoire leroy",
    "rue guido gezelle",
    "rue guillaume kennis",
    "rue gustave fuss",
    "rue gustave huberti",
    "rue hancart",
    "rue henri bergé",
    "rue henri chomé",
    "rue henri evenepoel",
    "rue henri jacobs",
    "rue henri stacquet",
    "rue henri villard",
    "rue herman",
    "rue herman richir",
    "rue hubert krains",
    "rue huberti gustave",
    "rue iwan gilkin",
    "rue jacques jansen",
    "rue jacques rayé",
    "rue james watt",
    "rue jansen jacques",
    "rue jean blockx",
    "rue jean-baptiste brems",
    "rue jenatzy",
    "rue jolly",
    "rue josaphat",
    "rue joseph brand",
    "rue joseph coosemans",
    "rue joseph jacquet",
    "rue joseph van camp",
    "rue joseph wauters",
    "rue josse impens",
    "rue jules destrée",
    "rue jules lebrun",
    "rue julius hoste",
    "rue kessels",
    "rue knapen",
    "rue lebrun jules",
    "rue lefèvre victor",
    "rue lefrancq",
    "rue léon frédéric",
    "rue léon mignon",
    "rue léopold courouble",
    "rue liedts",
    "rue linné",
    "rue l'olivier",
    "rue louis socquet",
    "rue marbotin adolphe",
    "rue marguerite van de wiele",
    "rue mariën",
    "rue massaux",
    "rue masui",
    "rue max roos",
    "rue meert charles",
    "rue merckaert",
    "rue metsys",
    "rue monrose",
    "rue nestor de tière",
    "rue nicolas defrêcheux",
    "rue paul devigne",
    "rue paul hymans",
    "rue paul leduc",
    "rue philomène",
    "rue pierre theunis",
    "rue pierron sander",
    "rue portaels",
    "rue potagère",
    "rue quinaux",
    "rue rasson",
    "rue renkin",
    "rue richard vandevelde",
    "rue roelandts",
    "rue rogier",
    "rue roosevelt théodore",
    "rue royale",
    "rue royale-sainte-marie",
    "rue rubens",
    "rue sander pierron",
    "rue scutenere",
    "rue seutin",
    "rue séverin fernand",
    "rue simoens camille",
    "rue snieders auguste",
    "rue stacquet henri",
    "rue stephenson",
    "rue stijn streuvels",
    "rue streuvels stijn",
    "rue tassiers suzanne",
    "rue teniers",
    "rue théo coopman",
    "rue théodore roosevelt",
    "rue theunis pierre",
    "rue thiéffry",
    "rue thomas vinçotte",
    "rue van de wiele margerite",
    "rue van droogenbroeck",
    "rue van dyck",
    "rue van hammé",
    "rue van hasselt andré",
    "rue van hoorde",
    "rue van hove",
    "rue van oost",
    "rue van schoor",
    "rue van ysendyck",
    "rue vandenbussche",
    "rue vanderlinden",
    "rue vandermeersch",
    "rue vandeweyer",
    "rue verbist",
    "rue verboeckhaven",
    "rue vergote",
    "rue verhas",
    "rue verte",
    "rue verwée alfred",
    "rue victor hugo",
    "rue victor lefèvre",
    "rue victor oudart",
    "rue victor vanderhoeft",
    "rue vifquin",
    "rue vinçotte thomas",
    "rue vogler",
    "rue vonck",
    "rue vondel",
    "rue waelhem",
    "rue walckiers",
    "rue watt james",
    "rue wauters joseph",
    "rue willem kuhnen",
    "rue wittmann emile",
    "sentier des pommes",
    "square emile duployé",
    "square eugène plasky",
    "square françois riga",
    "square levie",
    "square prévost-delaunay",
    "square riga françois",
    "square vergote"
];

// impetrantsNames1030
const impetrantsNames1030 = [
    "BELIRIS",
    "BM-DEN",
    "BM-DPV",
    "COLT",
    "DIGI",
    "ELIA",
    "EUROFIBER",
    "IRISNET",
    "PROXIMUS",
    "SCHAERBEEK AMÉNAGEMENT COMPLET",
    "SCHAERBEEK ASPHALTE",
    "SCHAERBEEK DAV",
    "SCHAERBEEK RENOVAS",
    "SCHAERBEEK TROTTOIRS",
    "SIBELGA",
    "SIBELGA EP",
    "SPRB",
    "STIB",
    "VIVAQUA ASSAINISSEMENT",
    "VIVAQUA DISTRIBUTION",
    "VIVAQUA RÉPARTITION",
    "VOO",
    "WYRE"
];

const impetrantsNames1030_ALL = [
    "BELIRIS",
    "BM-DEN",
    "BM-DPV",
    "BRUTELE",
    "COLT",
    "DITP",
    "ELIA",
    "EUROFIBER",
    "INFRABEL",
    "IRISNET",
    "PROXIMUS",
    "SCHAERBEEK AMÉNAGEMENT COMPLET",
    "SCHAERBEEK ASPHALTE",
    "SCHAERBEEK DAV",
    "SCHAERBEEK MARQUAGE",
    "SCHAERBEEK RENOVAS",
    "SCHAERBEEK TROTTOIRS",
    "SIBELGA",
    "SIBELGA EP",
    "VIVAQUA ASSAINISSEMENT",
    "VIVAQUA DISTRIBUTION",
    "VIVAQUA RÉPARTITION",
    "VOO",
    "WYRE",
    "DIGI",
    "STIB",
];

// Fermeture
const fermetureRue1030 = [
    "oui",
    "non"
];

// Función para poblar el datalist
function populateDatalist(listId, dataArray) {
    const datalist = document.getElementById(listId);

    // Asegúrate de que el datalist exista
    if (datalist) {
        datalist.innerHTML = ""; // Clear existing options
        // Itera sobre el array de datos
        dataArray.forEach(item => {
            // Crea un nuevo elemento <option>
            const option = document.createElement('option');

            // Asigna el valor del array al atributo 'value' de la opción
            option.value = item;

            // Agrega la opción al datalist
            datalist.appendChild(option);
        });
    } else {
        console.error(`Datalist con ID "${listId}" no encontrado.`);
    }
}

function ListaPropiedad(nombrePropiedad, origenDatos) {
    const valoresUnicos = new Set();

    // Nos aseguramos de tratar el origen como una lista, 
    // por si el usuario pasa un array [ProjectsChantiers1030]
    const fuentes = Array.isArray(origenDatos) ? origenDatos : [origenDatos];

    fuentes.forEach(fuente => {
        if (fuente && fuente.features) {
            fuente.features.forEach(feature => {
                // Accedemos al valor de la propiedad dentro de 'properties'
                const valor = feature.properties[nombrePropiedad];

                // Solo agregamos valores que no sean nulos o vacíos
                if (valor !== undefined && valor !== null && valor !== "") {
                    valoresUnicos.add(valor);
                }
            });
        }
    });

    // Convertimos el Set a un Array y lo ordenamos alfabéticamente
    return Array.from(valoresUnicos).sort();
}

// Evento que se dispara cuando el DOM está completamente cargado

const streetNames1030_0 = ListaPropiedad("VoirieNom", [ProjectsChantiers1030]);
document.addEventListener('DOMContentLoaded', (event) => {
    // Llama a la función para poblar el datalist 
    populateDatalist('datalist_StreetFR', streetNames1030_0);
});

const impetrantsNames1030_0 = ListaPropiedad("NomImpetrant", [ProjectsChantiers1030]);
document.addEventListener('DOMContentLoaded', (event) => {
    // Llama a la función para poblar el datalist 
    populateDatalist('datalist_Impetrants', impetrantsNames1030_0);
});

const fermetureRue1030_0 = ListaPropiedad("FermetureRue", [ProjectsChantiers1030]);
document.addEventListener('DOMContentLoaded', (event) => {
    // Llama a la función para poblar el datalist 
    populateDatalist('datalist_FermetureRue', fermetureRue1030_0);
});