// streetsNames1030
const streetNames1030 = [
    "allée des freesias",
    "autoroute e40",
    "avenue adolphe lacomblé",
    "avenue albert desenfans",
    "avenue albert giraud",
    "avenue ambassadeur van vollenhoven",
    "avenue britsiers",
    "avenue charbo",
    "avenue charles gilisquet",
    "avenue chazal",
    "avenue clays",
    "avenue colonel picquart",
    "avenue dailly",
    "avenue de cortenbergh",
    "avenue de février",
    "avenue de la brabançonne",
    "avenue de la jeunesse",
    "avenue de la reine",
    "avenue de la topaze",
    "avenue de l'emeraude",
    "avenue de l'héliport",
    "avenue de l'opale",
    "avenue de mai",
    "avenue de mars",
    "avenue de roodebeek",
    "avenue des azalées",
    "avenue des capucines",
    "avenue des cerisiers",
    "avenue des clos",
    "avenue des constellations",
    "avenue des glycines",
    "avenue des héliotropes",
    "avenue des jacinthes",
    "avenue des jardins",
    "avenue docteur dejase",
    "avenue du diamant",
    "avenue du fléau d'armes",
    "avenue du frioul",
    "avenue du pentathlon",
    "avenue du prince héritier",
    "avenue du suffrage universel",
    "avenue emile max",
    "avenue emile verhaeren",
    "avenue emile zola",
    "avenue ernest cambier",
    "avenue ernest renan",
    "avenue eugène demolder",
    "avenue eugène plasky",
    "avenue félix marchal",
    "avenue fortin",
    "avenue frans courtens",
    "avenue général eisenhower",
    "avenue général lartigue",
    "avenue georges eekhoud",
    "avenue georges rodenbach",
    "avenue gustave latinis",
    "avenue henri conscience",
    "avenue henry dunant",
    "avenue herbert hoover",
    "avenue huart hamoir",
    "avenue jacques georgin",
    "avenue jan stobbaerts",
    "avenue jean jaurès",
    "avenue léon mahillon",
    "avenue léonard mommaerts",
    "avenue léopold iii",
    "avenue louis bertrand",
    "avenue maréchal foch",
    "avenue maurice maeterlinck",
    "avenue milcamps",
    "avenue mon plaisir",
    "avenue paul deschanel",
    "avenue philippe thomas",
    "avenue prekelinden",
    "avenue princesse elisabeth",
    "avenue raymond foucart",
    "avenue rogier",
    "avenue sleeckx",
    "avenue voltaire",
    "avenue zénobe gramme",
    "boulevard auguste reyers",
    "boulevard brand whitlock",
    "boulevard des quatre journées",
    "boulevard du roi albert ii",
    "boulevard général wahis",
    "boulevard lambermont",
    "boulevard léopold iii",
    "boulevard simon bolivar",
    "chaussée de haecht",
    "chaussée de helmet",
    "chaussée de louvain",
    "chaussée de roodebeek",
    "chemin du forgeron",
    "cité ouvrière de linthout",
    "clos de la ballade",
    "clos de la pastourelle",
    "clos de l'oasis",
    "clos des artistes",
    "clos des fleurs",
    "clos des mouettes",
    "clos des poètes",
    "clos du chemin creux",
    "drève recteur van waeyenbergh",
    "grande rue au bois",
    "inconnu (tunnel sncb)",
    "petite rue des secours",
    "petite rue l'olivier",
    "place colignon",
    "place de jamblinne de meux",
    "place de la patrie",
    "place de la reine",
    "place des carabiniers",
    "place des chasseurs ardennais",
    "place eugène verboekhoven",
    "place gaucheret",
    "place lehon",
    "place liedts",
    "place solvay",
    "place stephenson",
    "place terdelt",
    "rampe du lion",
    "rue achille detienne",
    "rue adolphe marbotin",
    "rue aimé smekens",
    "rue albert de latour",
    "rue alexandre de craene",
    "rue alexandre markelbach",
    "rue allard",
    "rue anatole france",
    "rue andré van hasselt",
    "rue armand de roo",
    "rue artan",
    "rue arthur roland",
    "rue august de boeck",
    "rue auguste lambiotte",
    "rue auguste snieders",
    "rue bordiau",
    "rue brichaut",
    "rue calvin",
    "rue camille simoens",
    "rue camille wollès",
    "rue caporal claes",
    "rue capronnier",
    "rue charles degroux",
    "rue charles meert",
    "rue charles quint",
    "rue charles van lerberghe",
    "rue charles vanderstappen",
    "rue chaumontel",
    "rue colonel bourg",
    "rue cornet de grez",
    "rue creuse",
    "rue d'aerschot",
    "rue d'anethan",
    "rue de beughem",
    "rue de brabant",
    "rue de genève",
    "rue de jérusalem",
    "rue de la besace",
    "rue de la bruyère",
    "rue de la chaumière",
    "rue de la cible",
    "rue de la consolation",
    "rue de la constitution",
    "rue de la fraternité",
    "rue de la limite",
    "rue de la luzerne",
    "rue de la marne",
    "rue de la poste",
    "rue de la résistance",
    "rue de la ruche",
    "rue de l'abondance",
    "rue de l'agriculture",
    "rue de l'ecuelle",
    "rue de l'est",
    "rue de linthout",
    "rue de locht",
    "rue de l'orme",
    "rue de moerkerke",
    "rue de pavie",
    "rue de picardie",
    "rue de potter",
    "rue de quatrecht",
    "rue de robiano",
    "rue des ailes",
    "rue des chardons",
    "rue des compagnons",
    "rue des confédérés",
    "rue des coteaux",
    "rue des mimosas",
    "rue des palais",
    "rue des pâquerettes",
    "rue des patriotes",
    "rue des pavots",
    "rue des pensées",
    "rue des plantes",
    "rue désiré desmet",
    "rue destouvelles",
    "rue d'hoogvorst",
    "rue docteur elie lambotte",
    "rue du château",
    "rue du corbeau",
    "rue du dahlia",
    "rue du foyer schaerbeekois",
    "rue du moulin",
    "rue du noyer",
    "rue du pavillon",
    "rue du pont de l'avenue",
    "rue du progrès",
    "rue du radium",
    "rue du saphir",
    "rue du soleil",
    "rue du tilleul",
    "rue dupont",
    "rue edouard deknoop",
    "rue edouard fiers",
    "rue edouard stuckens",
    "rue eeckelaers",
    "rue emile wittmann",
    "rue emmanuel hiel",
    "rue ernest discailles",
    "rue ernest laude",
    "rue eugène smits",
    "rue fernand séverin",
    "rue floris",
    "rue fontaine d'amour",
    "rue fraikin",
    "rue françois bossaerts",
    "rue françois degreef",
    "rue françois-joseph navez",
    "rue frans binjé",
    "rue frans courtens",
    "rue frédéric pelletier",
    "rue gallait",
    "rue gaucheret",
    "rue geefs",
    "rue gendebien",
    "rue général eenens",
    "rue général gratry",
    "rue georges garnir",
    "rue georges raeymaekers",
    "rue georges rency",
    "rue gérard",
    "rue glibert",
    "rue godefroid devreese",
    "rue godefroid guffens",
    "rue godefroid kurth",
    "rue goossens",
    "rue grégoire leroy",
    "rue guido gezelle",
    "rue guillaume kennis",
    "rue gustave fuss",
    "rue gustave huberti",
    "rue hancart",
    "rue henri bergé",
    "rue henri chomé",
    "rue henri evenepoel",
    "rue henri jacobs",
    "rue henri stacquet",
    "rue henri van hamme",
    "rue henry villard",
    "rue herman",
    "rue herman richir",
    "rue hobbema",
    "rue hubert krains",
    "rue iwan gilkin",
    "rue jacques jansen",
    "rue jacques rayé",
    "rue james watt",
    "rue jan blockx",
    "rue jan frans de craen",
    "rue jean-baptiste brems",
    "rue jenatzy",
    "rue jolly",
    "rue josaphat",
    "rue joseph brand",
    "rue joseph coosemans",
    "rue joseph jacquet",
    "rue joseph van camp",
    "rue joseph wauters",
    "rue josse impens",
    "rue jul merckaert",
    "rue jules destrée",
    "rue jules lebrun",
    "rue julius hoste",
    "rue kessels",
    "rue knapen",
    "rue lefrancq",
    "rue léon de lantsheere",
    "rue léon frédéric",
    "rue léon mignon",
    "rue léopold courouble",
    "rue liedts",
    "rue linné",
    "rue l'olivier",
    "rue louis scutenaire",
    "rue louis socquet",
    "rue luther",
    "rue marcel marïen",
    "rue marguerite van de wiele",
    "rue massaux",
    "rue masui",
    "rue maurice des ombiaux",
    "rue max roos",
    "rue metsys",
    "rue monrose",
    "rue murillo",
    "rue nestor de tière",
    "rue nicolas defrêcheux",
    "rue paul devigne",
    "rue paul hymans",
    "rue paul leduc",
    "rue philomène",
    "rue pierre alderson",
    "rue pierre mattheussens",
    "rue pierre theunis",
    "rue portaels",
    "rue potagère",
    "rue quinaux",
    "rue rasson",
    "rue renkin",
    "rue richard vandevelde",
    "rue roelandts",
    "rue rogier",
    "rue rouen-bovie",
    "rue royale",
    "rue royale-sainte-marie",
    "rue rubens",
    "rue sander pierron",
    "rue seutin",
    "rue stephenson",
    "rue stijn streuvels",
    "rue stroobants",
    "rue teniers",
    "rue théo coopman",
    "rue théodore roosevelt",
    "rue thiéfry",
    "rue thomas vinçotte",
    "rue van campenhout",
    "rue van droogenbroeck",
    "rue van dyck",
    "rue van hammée",
    "rue van hoorde",
    "rue van hove",
    "rue van oost",
    "rue van ostade",
    "rue van schoor",
    "rue van ysendyck",
    "rue vandenbussche",
    "rue vanderlinden",
    "rue vandermeersch",
    "rue vandeweyer",
    "rue verbist",
    "rue verboeckhaven",
    "rue vergote",
    "rue verhas",
    "rue verte",
    "rue verwée",
    "rue victor hugo",
    "rue victor lefèvre",
    "rue victor oudart",
    "rue victor vanderhoeft",
    "rue vifquin",
    "rue vogler",
    "rue vonck",
    "rue vondel",
    "rue waelhem",
    "rue walkiers",
    "rue wappers",
    "rue willem de mol",
    "rue willem kuhnen",
    "rue william degouve de nuncques",
    "square apollo",
    "square armand steurs",
    "square de l'accueil",
    "square emile duployé",
    "square françois riga",
    "square vergote",
    "tunnel belliard",
    "tunnel reyers-centre",
    "tunnel reyers-meiser",
    "tunnel reyers-montgomery",
    "viaduc e40",
    "viaduc reyers",
];


// Variable globale qui contiendra la liste des rues partagées, excluant la rue principale
let streetNames1030_C = [];

// Fonction utilitaire pour peupler un datalist
function populateDatalist(listId, dataArray) {
    const datalist = document.getElementById(listId);
    if (datalist) {
        datalist.innerHTML = ""; // Nettoie le datalist avant d'ajouter de nouvelles options
        dataArray.forEach(item => {
            const option = document.createElement('option');
            option.value = item;
            datalist.appendChild(option);
        });
    }
}

// Le script principal s'exécute lorsque le DOM est prêt
document.addEventListener('DOMContentLoaded', () => {

    // 1. Initialise le premier datalist
    populateDatalist('datalist_StreetFR_01', streetNames1030);

    const inputCalle = document.getElementById('RoadwayName_FR');

    if (inputCalle) {
        inputCalle.addEventListener('input', (e) => {
            const choixUtilisateur = e.target.value;

            // Gestion du cas où le champ est effacé par l'utilisateur
            if (!choixUtilisateur) {
                document.getElementById('datalist_StreetFR_02').innerHTML = "";
                return;
            }

            // Recherche de la rue principale dans le GeoJSON
            const featureTrouvee = URBIS_OSIRIS_GroupStreet_OnlyNodes.features.find(feature =>
                feature.properties.PW_NAME_FR === choixUtilisateur
            );

            if (featureTrouvee) {
                // Traitement de la liste :
                const rawArray = featureTrouvee.properties.name_street_shared
                    .split(',')
                    .map(s => s.trim());

                // --- LA NOUVEAUTÉ EST ICI ---
                // 2. Filtrer pour exclure la rue principale de la liste partagée
                const filteredArray = rawArray.filter(name => name !== choixUtilisateur);

                // 3. Éliminer les duplicatas et trier alphabétiquement
                streetNames1030_C = [...new Set(filteredArray)].sort((a, b) => a.localeCompare(b));

                console.log("const streetNames1030_C =", streetNames1030_C);

                // 4. Peupler le second datalist avec la nouvelle liste filtrée
                populateDatalist('datalist_StreetFR_02', streetNames1030_C);
            }
        });
    }
});